# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - ldflags:
    - -s -w -X main.Version=v{{.Version}} -X main.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - repository:
      owner: matthieugusmini
      name: homebrew-tap
    commit_author:
      name: "Matthieu Gusmini"
      email: "simfy2602@outlook.fr"
    homepage: "https://github.com/matthieugusmini/rift"
    description: "LoL Esports in your terminal"
    license: mit

nix:
  - repository:
      owner: matthieugusmini
      name: nur
    homepage: "https://github.com/matthieugusmini/rift"
    description: "LoL Esports in your terminal"
    license: mit

dockers:
  - image_templates:
    - ghcr.io/matthieugusmini/{{ .ProjectName }}:v{{ .Version }}-arm64
    use: buildx
    goarch: arm64
    build_flag_templates :
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
    - ghcr.io/matthieugusmini/{{ .ProjectName }}:v{{ .Version }}-amd64
    use: buildx
    goarch: amd64
    build_flag_templates :
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: ghcr.io/matthieugusmini/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/matthieugusmini/{{ .ProjectName }}:v{{ .Version }}-arm64
      - ghcr.io/matthieugusmini/{{ .ProjectName }}:v{{ .Version }}-amd64
  - name_template: ghcr.io/matthieugusmini/{{ .ProjectName }}:v{{ .Version }}
    image_templates:
      - ghcr.io/matthieugusmini/{{ .ProjectName }}:v{{ .Version }}-arm64
      - ghcr.io/matthieugusmini/{{ .ProjectName }}:v{{ .Version }}-amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs.*"
      - "^test.*"
      - "^chore.*"
      - "^style.*"
      - "^ci.*"
      - "^refactor.*"
      - Initial commit
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
