# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  run:
    cmds:
      - go run .

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  logs:
    desc: Watch logs
    cmds:
      - cmd: tail -f ~/Library/Logs/rift/rift.log
        platforms: [darwin]
      - cmd: tail -f ~/.cache/rift/rift.log
        platforms: [linux]
