# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  APP_NAME: rift

tasks:
  run:
    cmds:
      - go run .

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  logs:
    desc: Watch logs
    cmds:
      - cmd: tail -f ~/Library/Logs/{{.APP_NAME}}/{{.APP_NAME}}.log
        platforms: [darwin]
      - cmd: tail -f ~/.cache/{{.APP_NAME}}/{{.APP_NAME}}.log
        platforms: [linux]

  generate-demo:
    desc: Generate a new demo GIF
    cmds:
      - vhs demo.tape

  publish-demo:
    desc: Publish the demo GIF
    cmds:
      - vhs publish demo.gif

